### ISSUE TITLE
Weird content-property-no-static-value

### ISSUE THREAD

**Issue by doasync** [YozhikM/stylelint-a11y#32]
![screenshot 1](https://user-images.githubusercontent.com/29141708/42816236-dd3b4b5a-89d2-11e8-9609-18634ccc3769.png)
![screenshot 2](https://user-images.githubusercontent.com/29141708/42816242-e010b374-89d2-11e8-9485-f3a9381e5354.png)

**Comment by YozhikM** [comment]
Which release version you have?

**Comment by doasync** [comment]
"stylelint-a11y": "^1.1.6",

**Comment by YozhikM** [comment]
@doasync In [1.1.7](https://github.com/YozhikM/stylelint-a11y/releases/tag/1.1.7) we released fix for this rule

**Comment by MechJosh0** [comment]
This rule prevents my VueJS app from running, if I include it inside the `.stylelintrc` config the app doesn't run. I'm using `1.1.7`.

**Comment by igorkamyshev** [comment]
We definitely fixed this bug in `1.1.8`. Try to update package, please.

**Comment by MechJosh0** [comment]
@igorkamyshev Fixed confirmed working. Thanks.

**Comment by nickmccurdy** [comment]
This can be closed
