### ISSUE TITLE
Missing recommended.js within the published archive file

### ISSUE THREAD

**Issue by ybiquitous** [YozhikM/stylelint-a11y#39]
Hi, I noticed `recommended.js` is missing within the published archive file to npm.

## Reproduction

Run the following commands on your terminal:

1. `curl -O $(npm v stylelint-a11y dist.tarball)`
2. `tar -xzvf stylelint-a11y-*.tgz`
3. `ls package/recommended.js` => `ls: package/recommended.js: No such file or directory`

## Environment

`stylelint-a11y` version: `1.1.10` (latest on 2019-04-06)

I would be happy if you would check it. Thanks.

**Comment by ybiquitous** [comment]
It's strange... 🤔  When I tried `npm pack` command on my local machine, `recommended.js` was included!

```shell
$ git clone https://github.com/YozhikM/stylelint-a11y.git

$ cd stylelint-a11y

$ npm install

$ npm pack
```

<img width="660" alt="image" src="https://user-images.githubusercontent.com/473530/55645477-a6593d80-5813-11e9-8b4c-3dd508f66bdd.png">

**Comment by YozhikM** [comment]
@ybiquitous You're absolutely right. I did not include the config in the release, so you got an error. Five minutes ago, I published a new release, you can check!

**Comment by ybiquitous** [comment]
@YozhikM Thank you very much! The new version `1.1.11` works fine! 🎉
