### ISSUE TITLE
stylelint-a11y 1.2.3 not available on npmjs.com

### ISSUE THREAD

**Issue by engelfrost** [YozhikM/stylelint-a11y#51]
I can't update to the latest patch because it's not available through the npm repository. 

https://www.npmjs.com/package/stylelint-a11y

**Comment by ybiquitous** [comment]
@YozhikM Could you please publish to npmjs.com?

**Comment by ybiquitous** [comment]
@YozhikM Thanks a lot! The new version has been published!

https://www.npmjs.com/package/stylelint-a11y
