### ISSUE TITLE
Incorrect peer dependency

### ISSUE THREAD

**Issue by schalkneethling** [YozhikM/stylelint-a11y#52]
Just installed stylelint-a11y as part of a fresh install on a new project using yarn with:

```
yarn add stylelint stylelint-config-standard stylelint-a11y --dev
```

Noticed the following in the output of Yarn:

```
warning " > stylelint-a11y@1.2.2" has incorrect peer dependency "stylelint@^8.0.0 || ^9.0.0 || ^10.0.0 || ^11.0.0".
```

**Comment by ybiquitous** [comment]
When PR #53 is published, this issue should be resolved.

**Comment by ybiquitous** [comment]
#53 is merged. When a new version is published, we can close this issue. 

/cc @YozhikM

**Comment by YozhikM** [comment]
@ybiquitous I'll release it in 10 mins. Check it later

**Comment by ybiquitous** [comment]
@YozhikM Thank you so much! I've confirmed that a new version has been published and resolved this peer-dep issue! 😊
