### ISSUE TITLE
License

### ISSUE THREAD

**Issue by igorkamyshev** [YozhikM/stylelint-a11y#6]
I can't find license file in repo. Maybe you may adding it?

**Comment by evilebottnawi** [comment]
@YozhikM MIT?

**Comment by YozhikM** [comment]
@evilebottnawi Yeah, I think this is a standard license for open source.

**Comment by evilebottnawi** [comment]
Feel free to send PR

**Comment by YozhikM** [comment]
I do it already directly :)

**Comment by evilebottnawi** [comment]
:+1:
